neogeny/TatSu

- tatsu/contexts.py
- test/grammar/left_recursion_test.py
Only the unit test. Allow right-associativity in lef+right recursion.
> Left assoc in left right recursion

- CHANGELOG.rst
- docs/syntax.rst
- grammar/tatsu.ebnf
- tatsu/bootstrap.py
- tatsu/codegen/python.py
- tatsu/contexts.py
- tatsu/grammars.py
- test/grammar/lookahead_test.py
The *"skip to"* expression; useful for writing *recovery* rules.
The parser will advance over input, one character at time, until ``e`` matches. Whitespace and comments will be skipped at each step.
The expression is equivalent to:
```ocaml
{ /./ !e} e
```
> Implemented the _skip to_ expression (`->`)

- tatsu/contexts.py
- test/grammar/left_recursion_test.py
closes #27 
* Move left-recursion memos to starting position for expression to stop dropping input
* Take ideas from Grako's implementation of Warth's
* One of the grammars in the unit tests is probably incorrect, and making it work was forcing the parser to fail on completely reasonable use cases. 
* Refactor for brevity and clarity
> Refactor left-recursion support

- docs/left_recursion.rst
- tatsu/contexts.py
- test/grammar/left_recursion_test.py
*   The recursion logic takes care of cleaning up its caches. Having memoization
intervene produces unexpected results.
*   Document how not all left-recursive grammars that use the TatSu syntax are PEG-left.
closes #34
> [left_recursion_and_cut] memoization should not affect memoization results

- CHANGELOG.rst
- README.rst
- docs/contributors.rst
- docs/mini-tutorial.rst
- examples/calc/calc.py
- tatsu/contexts.py
- test/grammar/left_recursion_test.py
*   #27 Undo the fixes to dropped input on left recursion because they broke previously expected behavior.
*   #33 Fixes to the calc example and mini tutorial (@heronils)
*   #34 More left-recursion test cases (@manueljacob).
> revert changes dropped input in left-recursion

- docs/use.rst
The json.dumps line in "Using the Tool" section of Tatsu docs do not reflect the line in the README. An error was raised (raise TypeError(repr(o) + " is not JSON serializable")) when using json.dumps without asjson(). Updating that line to the code in README now works as intended.
> Updated use.rst because json.dumps raised error

- tatsu/parser.py
- test/parsing_test.py
This is most likely some kind of regression but I didn't bother checking when it occurred. Note that this didn't work in Grako for some time now, aswell.
Including files via the pragma does not work, because the `GrammarGenerator` that subclasses `EBNFBootstrapParser` does not use the `EBNFBuffer` class as its `buffer_class` but the default one from the parent class constructor. The default one lacks the ability to include files.
These two commits provide a test case (more of an integration test) and a fix for that.
Cheers!
> Regression fix: including file does not work because EBNFBuffer is not used

- CHANGELOG.rst
- README.rst
- docs/use.rst
- tatsu/codegen/python.py
- tatsu/tool.py
- tatsu/util.py
*   previously 'start' was forced upon generated parsers
*   also make the `start=` argument to `parse()` explicit in the docs
fixes #40
> [start_symbol] make parsers use the first rule in the grammar as default start rule

- tatsu/parser_semantics.py
> Import 're' from tatsu.util to support optional 'regex'-only features

- tatsu/contexts.py
- test/parsing_test.py
According to the documentation in docs/syntax.rst, rule names that start with an uppercase character do not advance over whitespace before beginning to parse. Currently, there are some issues in the implementation of this.
Right now the logic checks to see if the entire rule name is lowercase before advancing over whitespace. This pull request fixes it so it only checks the first letter. It looks like this bug originally came from here: https://github.com/neogeny/TatSu/commit/3f57ab620f35ccd27746372e53a8c6c0e6ddb3a7#diff-db601756bf2cb00180df4b281f5bcf9aL490
This can be tested with the following test:
```python
import tatsu
def make_test_grammar( rule_name, rule_syntax ):
grammar_template = "start = 'hello' %s $ ; %s = %s ;"
return grammar_template % (rule_name, rule_name, rule_syntax) …
```
> Only care about case of first letter of rule name

- docs/syntax.rst
Fix the RST headline markup of "Reserved Words and Keywords" and " Include
Directive". This typo made these two sections not visible in the table of
contents.
> Fix the RST syntax of two headlines

- tatsu/grammars.py
Ensures grammars have no comment regexes until defined. Fixes #59. I don't think this breaks any functionality (the tests still pass) except grammars that relied on a preset comment definition.
> Use normal buffer for parsing grammars.

- docs/contributing.rst
a tiny edit to a tiny doc file.
i'm guessing some time after the transition from Grako to TatSu, hosting of the repository changed from bitbucket to github. but nonetheless there remains an old link pointing to a nonexistent bitbucket repository. hopefully this updated link is the correct, "official" link for contributing. Thanks!
> [docs] contributing: update link s/bitbucket/github

- docs/mini-tutorial.rst
There is no `parse_with_basic_semantics` honoured by `tatsu.compile()`, only `semantics` is honoured.
This PR fixes the error in the documentation.
> parse_with_basic_semantics -> semantics

- tatsu/grammars.py
Fixes #71 
Was causing commented out directives to fail on tuple unpacking if there was more than one `::` on the line.
> Limit pragma split to 2 elements

- docs/use.rst
- tatsu/tool.py
Change "left-recusion" to "left-recursion".
> Fix typo in command-line help

- tatsu/contexts.py
There was a small typo in a method name.
> Fix typo in method name

- Makefile
The `find` command on BSD variants requires a path before any find expression.
> Fix errors in Makefile for macOS

- tatsu/buffering.py
- tatsu/grammars.py
- tatsu/tool.py
- test/grammar/directive_test.py
In the multiple passing of settings between parser layers, the value of `@@nameguard` was not making it to the `Buffer` class.
fixes #95
> [nameguard] fix @@nameguard not being honored

- tatsu/containers.py
- tatsu/grammars.py
In python 3.8 classes from `collections.abc` cannot be imported by importing from
`collections`. Therefore some imports needed to be changed.
> Replaced imports from `collections` to `collections.abc` for python 3.8

- grammar/tatsu.ebnf
- tatsu/bootstrap.py
- tatsu/codegen/python.py
- tatsu/contexts.py
- tatsu/grammars.py
Grammar rules have the `is_memoizable` attribute profuct of the implementation of leftrec.
These changes expose the attribute as a grammar decorator for rules.
> Implement the @nomemo decorator for grammar rules

- tatsu/contexts.py
- tatsu/grammars.py
- tatsu/parser_semantics.py
- test/grammar/directive_test.py
- test/grammar/join_test.py
- test/grammar/left_recursion_test.py
- test/grammar/lookahead_test.py
- test/grammar/pattern_test.py
- test/grammar/syntax_test.py
The result of parsing a sequence was the same as parsing a closure: list/closure(list).
This change makes the result of sequences be `tuple`:
* a minor change in the ast-generating code
* an important backwards incompatibility
* a huge improvement in AST semantics
* an important improvement in runtime efficiency
> [ast] make the result of sequences be `tuple`

- CHANGELOG.rst
- grammar/tatsu.ebnf
- tatsu/bootstrap.py
- tatsu/codegen/python.py
- tatsu/g2e/semantics.py
- tatsu/grammars.py
- test/grammar/defines_test.py
* Add a new `Option` node type to the model in `tatsu\grammars`  
* Add defines within `Optional` elements
* Skip `Rule` defines when `exp` is a `Choice`
fixes #202
> Add Choice->Option node to grammar model with defines

- docs/syntax.rst
- grammar/tatsu.ebnf
- tatsu/bootstrap.py
- tatsu/codegen/python.py
- tatsu/contexts.py
- tatsu/grammars.py
- tatsu/infos.py
- test/grammar/alerts_test.py
^``constant``
An alert. There will be no token returned by the parser, but an alert will be registed in the parse context and added to the current node's `parseinfo`.
The `^` character may appear more than once to indicate the alert level.
```
assignment = identifier '=' (
| value
| ->'&; ^^^`could not parse value in assignment to {identifier}`
```
> [grammar][parser] add 'alert' expressions to grammar

- CHANGELOG.rst
- docs/syntax.rst
- tatsu/contexts.py
The easy optimizations available under the traditional semantics would be lost if cut doesn't escape a rule.
The grammar would have to add lookaheads to each option in a choice to achieve the same, while previously adding a cut after a keyword was enough.
> [contexts] revert cut expressions applying only to local rule

- docs/use.rst
- tatsu/bootstrap.py
- tatsu/codegen/python.py
- tatsu/grammars.py
- tatsu/infos.py
- test/parser_equivalence_test.py
- test/parsing_test.py
There were some confusion around the `rule_name` / `start` argument to the `parse()` method. These patches hopefully fix that. I haven't understood what is the role of `start_rule` in the `ParserConfig` dataclass but I suspect it is there for backward compatibility with generated parsers, thus I didn't touch it.
This may require regenerating the bootstrapped EBNF parser.
> Fixes for initial grammar rule handling

- test/parser_equivalence_test.py
There is no need to write the code in a file to load it as a module.
It can be done without touching the filesystem and thus potentially
leaving temporary files around.
> [tests] Modernize how generated code is loaded

- examples/calc/calc.py
- examples/calc/codegen.py
- test/__init__.py
- test/__main__.py
- test/ast_test.py
- test/buffering_test.py
- test/codegen_test.py
- test/diagram_test.py
- test/grammar/directive_test.py
- test/grammar/firstfollow_test.py
- test/grammar/join_test.py
- test/grammar/keyword_test.py
- test/grammar/left_recursion_test.py
- test/grammar/lookahead_test.py
- test/grammar/parameter_test.py
- test/grammar/pattern_test.py
- test/grammar/pretty_test.py
- test/grammar/semantics_test.py
- test/grammar/stateful_test.py
- test/grammar/syntax_test.py
- test/model_test.py
- test/parsing_test.py
- test/walker_test.py
PEP 479, StopIteration handling inside generators, enabled by 'from
__future__ import generator_stop' is the default since Python 3.7 and
thus for all supported Python releases.
https://docs.python.org/3.10/library/__future__.html
> [treewide] Remove 'from __future__ import generator_stop'

- tatsu/util/_common.py
The __str__() method of Node returns a JSON representation of the
Node. This fails if the Node contains anything that cannot be
represented by plain JSON. Notable examples are datetime and date
objects that are not so unrealistic for a parser to return.
Use a custom JSON encoder that fall back to repr() for these objects
so that a string representation for a Node can always be returned.
Fixes #262.
> [model] Fall back to repr() for objects not handled by json module

- docs/syntax.rst
Fix a couple of markups errors, a typo, and a couple of broken links.
Simplify the markup using "::" code blocks instead than explicit
".. code::" blocks for TatSu syntax and disable syntax highlighting
for these.
To make markup errors similar to the ones fixed here less likely, turn
the description of TatSu expression into regular paragraphs rather
than quoted paragraphs.
> [docs] Small fixes and markup simplification

- tatsu/rendering.py
Is the current behavior intended? Currently, argument `multiplier` passed are simply ignored.
> pass multiplier argument

- docs/directives.rst
- docs/mini-tutorial.rst
- docs/syntax.rst
The mini tutorial, when introducing grammar annotation, failed to add annotate the division expression.
s/alfanumeric/alphanumeric/ along with s/alfarnumeric/alphanumeric/ in the directives documentation.
Remove whitespace between @ or @@ and the directive when discussing reserved word handling in the syntax documentation, consistent with how directives are formatted elsewhere.
> add missing annotation in tutorial, typo and whitespace cleanup

- tatsu/infos.py
Note: This is untested and I don't have time/energy to do any more on this, so if no one wants to wrap it up, feel free to close it.
Noticed this while profiling ics-py which felt really slow (even considering large ics files and it being python).
Would speed up https://github.com/ics-py/ics-py ~~3%~~ ~7% so not that much, but maybe worth a few line changes.
(github refuse to upload the py-spy profile..)
> Pre-compile regexps

- docs/directives.rst
- docs/syntax.rst
- grammar/tatsu.ebnf
- tatsu/bootstrap.py
- tatsu/buffering.py
- tatsu/codegen/objectmodel.py
- tatsu/codegen/python.py
- tatsu/g2e/semantics.py
- tatsu/grammars.py
- tatsu/infos.py
- tatsu/ngcodegen/python.py
- tatsu/util/_common.py
- tatsu/walkers.py
- test/grammar/pattern_test.py
- test/grammar/syntax_test.py
- test/parser_equivalence_test.py
There are numerous changes in this MR,
1. Update the default eol_comments pattern to use `(?m)`. Since bootstrap.py was not regenerated after #338, tests didnt fail like they should have, however users trying to generate code in the new version got bit by a behavior change. 
One of the reasons this got missed is because the code generator uses `repr` and there's apparently no test to compare the current bootstrap.py with a newly generated file from `grammar/tatsu.ebnf` so this test may be worth adding at some point.
2. Drop the forced `re.MULTILINE` injection to `str` type regex patterns per discussion https://github.com/neogeny/TatSu/issues/351#issuecomment-2563635784
2. Document the behavior change regarding `re.MULTILINE` match no longer being injected into regex string patterns …
> Make {eol_}comments_re read-only and non-init arguments in `ParserConfig`

- .github/workflows/default.yml
- requirements-test.txt
- ruff.toml
The main goals of this PR are: update outdated actions, reduce the runtime, streamline and simplify. Not installing unnecessary packages and not updating the installation with apt reduces the tests runtime from above 6 minutes to less than a minute.
> [ci] modernize

- docs/contributors.rst
- docs/links_contributors.rst
- tatsu/grammars.py
globals().values() creates an iterator. If the thread changes in the middle of the comprehension and the globals dict is modified, we end up with the following error:
```
RuntimeError: dictionary changed size during iteration
```
To avoid that, we make a copy and iterate over that, to avoid concurrency issues.
> Fix non-thread-safe access of globals()

- docs/contributors.rst
- docs/links_contributors.rst
- test/grammar/parameter_test.py
In `test_36_unichars` we are writing local python file and them import it for testing purposes.
So far this was done in a local directory (current working dir), but this is not ideal, as it might not be on a writable filesystem. For that reason it seems better to use a temporary directory, that is much more commonly provided in a writable form.
This PR proposes that shift.
> Use temp directory instead of cwd for test storage
