neogeny/TatSu

- CHANGELOG.md
- tatsu/contexts.py
- tatsu/infos.py
- tatsu/test/grammar/left_recursion_test.py
Use a memoization cache for parsed recursive results.
> Implement left recursion correctly

- CHANGELOG.rst
- docs/syntax.rst
- grammar/tatsu.ebnf
- tatsu/bootstrap.py
- tatsu/codegen/python.py
- tatsu/contexts.py
- tatsu/grammars.py
- test/grammar/syntax_test.py
The *any* expression, matches the next position in the input. It works exactly like the ``?'.'`` pattern, but is implemented at the buffer level, without using regular expressions.
> Added the _any_ expression

- test/grammar/left_recursion_test.py
> Add failing test for issue #27: Parser drops part of input

- tatsu/bootstrap.py
- tatsu/buffering.py
- tatsu/codegen/python.py
- tatsu/util.py
> [whitespace_inconsistency] be consistent about handling of whitespace::

- CHANGELOG.rst
- docs/contributors.rst
- tatsu/codegen/python.py
- test/grammar/pattern_test.py
fixes #66
https://scrapinghub.atlassian.net/browse/refs/heads/fix_multiline_re
> [fix_multiline_re] fix (?x) not supported in grammar

- tatsu/contexts.py
> Fix trace getting overwritten in generated parser

- tatsu/color.py
> [issue93_colorize] call colorama.init() for Windows sake

- grammar/tatsu.ebnf
- tatsu/bootstrap.py
- tatsu/codegen/python.py
- tatsu/parser_semantics.py
- test/grammar/directive_test.py
> [directives] allow None/False for @@whitespace

- tatsu/buffering.py
- test/buffering_test.py
> [buffering] fix lineinfo consistency

- tatsu/grammars.py
- test/grammar/semantics_test.py
> [models] also set optional attributes in Node

- test/grammar/left_recursion_test.py
> [leftrec_cleanup] clean up unit tests and issues related to leftrec

- test/grammar/left_recursion_test.py
@Victorious3 
I added this new test, and it's consistent with wat we talked about and expected.
> [test] test that left recursion accepts languages containing void

- tatsu/contexts.py
- test/grammar/left_recursion_test.py
Credit to @norswap for this one ^^
> Offset initial position to fix #116

- tatsu/objectmodel.py
- test/pickle_test.py
Addresses issue #144 using pickle only.
> Pickle fix for nested classes.

- test/misc_test.py
> add test for collections.abc warning

- tatsu/walkers.py
> Import ABC from collections.abc instead of collections for Python 3.9 compatibility

- CHANGELOG.rst
- docs/left_recursion.rst
> [docs] clarify limitations of left recursion in PEG

- docs/mini-tutorial.rst
* Add necessary imports and `if __main__` to all scripts
* Remove assumptions about folder structure, i.e. let the user decide where to save the files.
* Remove obsolete `codecs.open()` in favor of `with open()`
* Give concrete directions on assumed file names
* Fix missing change in grammar for the `codegen` paragraph.
* Update code for generated semantic model
* Simplify some wording.
> Make examples in the mini tutorial self-contained

- test/parser_equivalence_test.py
> [test] add test that shows that generated parser behaves differently

- .pylintrc
- README.md
- tatsu/contexts.py
- tatsu/grammars.py
- test/grammar/keyword_test.py
- test/parser_equivalence_test.py
- tox.ini
> [grammars] set keywords to uppercase if ignorecase

- tatsu/codegen/python.py
Fix proposal to have an ordered AST when generating a parser #164.
> fix: regression that loose the rules order #164

- tatsu/codegen/objectmodel.py
> [codegen] Use modern super() call in generated ModelBuilderSemantics

- tatsu/walkers.py
- test/walker_test.py
- test/zzz_bootstrap/bootstrap_test.py
> [walkers] ensure one cache per walker class

- tatsu/ast.py
- test/ast_test.py
- test/parser_equivalence_test.py
> [ast] fix pickling (@fizbin)

- CHANGELOG.rst
- docs/contributors.rst
- tatsu/walkers.py
Change the key used to store the walker from id(node.\_\_class__) to node.\_\_class__.\_\_qualname__.
> Fix NodeWalker methods

- CHANGELOG.rst
Contains also merge commit submitted in #283
> 5.7.4 Release

- test/parsing_test.py
> [test] Add test demonstrating expected white space skipping behavior

- README.rst
- tatsu/contexts.py
- tatsu/tokenizing.py
- test/parsing_test.py
fixes #305
[test] Add test demonstrating expected white space skipping behavior …
> Fix parseinfo.pos is not accurate

- Makefile
- docs/syntax.rst
- grammar/tatsu.ebnf
- tatsu/contexts.py
- tatsu/grammars.py
- test/grammar/alerts_test.py
- test/grammar/constants_test.py
> [semantics] evaluate `constant` to literals when possible

- tatsu/objectmodel.py
One option to fix https://github.com/neogeny/TatSu/issues/300
> Fix children when a child contains a nested dict

- docs/conf.py
- grammar/tatsu.ebnf
- tatsu/bootstrap.py
- tatsu/buffering.py
- tatsu/codegen/__init__.py
- tatsu/codegen/cgbase.py
- tatsu/codegen/objectmodel.py
- tatsu/codegen/python.py
- tatsu/collections/orderedset.py
- tatsu/contexts.py
- tatsu/diagrams.py
- tatsu/exceptions.py
- tatsu/g2e/semantics.py
- tatsu/grammars.py
- tatsu/infos.py
- tatsu/ngcodegen/python.py
- tatsu/objectmodel.py
- tatsu/parser_semantics.py
- tatsu/symtables.py
- tatsu/tool.py
- tatsu/util/_common.py
- tatsu/util/parproc.py
- test/grammar/keyword_test.py
- test/grammar/syntax_test.py
- test/parser_equivalence_test.py
- test/parsing_test.py
Setting ``@@whitespace`` to `None`, `False` was not being honored.
Also, allow strings as arguments to `@@whitespace``.
fixes #337
> Fix generated whitespace for :: None

- README.rst
> [docs] add note about TatSu-LTS in README.rst
